const logo = '/assets/logo.svg';
const product1 = '/assets/product1.jpg';
const product2 = '/assets/product2.jpg';
const product3 = '/assets/product3.jpg'; // sunglasses
const product4 = '/assets/product4.jpg'; // headphone
const product5 = '/assets/product5.jpg'; // speaker
const product6 = '/assets/product6.jpg'; // sneakers
const product7 = '/assets/product7.png'; // trolly bag
const model1 = '/assets/model1.png';
const model2 = '/assets/model2.jpg'; // model women
const generated1 = '/assets/generated1.png'; // men with trolly bag
const generated2 = '/assets/generated2.png'; // women with trolly bag
const generated3 = '/assets/generated3.png'; // men with shoes
const generated4 = '/assets/generated4.png'; // women with shoes
const generatedVideo1 = '/assets/generatedVideo1.mp4'; // random product men 9:16
const generatedVideo2 = '/assets/generatedVideo2.mp4'; // random product women 16:9

export const assets = {
    logo,
    product1,
    product2,
    product3,
    product4,
    product5,
    product6,
    product7,
    model1,
    model2,
    generated1,
    generated2,
    generated3,
    generated4,
    generatedVideo1,
    generatedVideo2,
};

export const dummyGenerations = [
    {
        id: 'gen_1',
        aspectRatio: '9:16',
        productDescription: 'Sky Colored Trolly Bag',
        productName: 'Trolly Bag',
        targetLength: 5,
        uploadedImages: [product7, model1],
        userId: 'user_1',
        userPrompt: 'Create the video where center of attraction is a trolly bag',
        generatedImage: generated1,
        generatedVideo: generatedVideo1,
        isGenerating: false,
        isPublished: false,
        createdAt: '2023-03-15T00:00:00.000Z',
        updatedAt: '',
    },
    {
        id: 'gen_2',
        aspectRatio: '16:9',
        productDescription: 'Stylish White Sneakers',
        productName: 'Sneakers',
        targetLength: 10,
        uploadedImages: [product6, model2],
        userId: 'user_2',
        userPrompt: 'Showcase the sneakers in a dynamic and fashionable way',
        generatedImage: generated4,
        generatedVideo: generatedVideo2,
        isGenerating: false,
        isPublished: true,
        createdAt: '2023-03-16T00:00:00.000Z',
        updatedAt: '',
    },
    {
        id: 'gen_3',
        aspectRatio: '9:16',
        productDescription: 'Classic Polaroid Camera',
        productName: 'Polaroid Camera',
        targetLength: 7,
        uploadedImages: [product2, model1],
        userId: 'user_1',
        userPrompt: 'Highlight the vintage appeal of the camera',
        generatedImage: product1,
        generatedVideo: generatedVideo1,
        isGenerating: false,
        isPublished: false,
        createdAt: '2023-03-17T00:00:00.000Z',
        updatedAt: '',
    },
    {
        id: 'gen_4',
        aspectRatio: '16:9',
        productDescription: 'Modern Wireless Headphones',
        productName: 'Headphones',
        targetLength: 8,
        uploadedImages: [product4, model2],
        userId: 'user_2',
        userPrompt: 'Emphasize the comfort and sound quality of the headphones',
        generatedImage: product2,
        generatedVideo: generatedVideo2,
        isGenerating: true,
        isPublished: false,
        createdAt: '2023-03-18T00:00:00.000Z',
        updatedAt: '',
    },
    {
        id: 'gen_5',
        aspectRatio: '9:16',
        productDescription: 'Classic Polaroid Camera',
        productName: 'Polaroid Camera',
        targetLength: 7,
        uploadedImages: [product2, model1],
        userId: 'user_1',
        userPrompt: 'Highlight the vintage appeal of the camera',
        generatedImage: product3,
        generatedVideo: generatedVideo1,
        isGenerating: false,
        isPublished: false,
        createdAt: '2023-03-17T00:00:00.000Z',
        updatedAt: '',
    },
    {
        id: 'gen_6',
        aspectRatio: '1:1',
        productDescription: 'Modern Wireless Headphones',
        productName: 'Headphones',
        targetLength: 8,
        uploadedImages: [product4, model2],
        userId: 'user_2',
        userPrompt: 'Emphasize the comfort and sound quality of the headphones',
        generatedImage: product4,
        generatedVideo: generatedVideo2,
        isGenerating: true,
        isPublished: false,
        createdAt: '2023-03-18T00:00:00.000Z',
        updatedAt: '',
    },
    {
        id: 'gen_7',
        aspectRatio: '9:16',
        productDescription: 'Classic Polaroid Camera',
        productName: 'Polaroid Camera',
        targetLength: 7,
        uploadedImages: [product2, model1],
        userId: 'user_1',
        userPrompt: 'Highlight the vintage appeal of the camera',
        generatedImage: product3,
        generatedVideo: generatedVideo1,
        isGenerating: false,
        isPublished: false,
        createdAt: '2023-03-17T00:00:00.000Z',
        updatedAt: '',
    },
    {
        id: 'gen_8',
        aspectRatio: '1:1',
        productDescription: 'Modern Wireless Headphones',
        productName: 'Headphones',
        targetLength: 8,
        uploadedImages: [product4, model2],
        userId: 'user_2',
        userPrompt: 'Emphasize the comfort and sound quality of the headphones',
        generatedImage: product4,
        generatedVideo: generatedVideo2,
        isGenerating: true,
        isPublished: false,
        createdAt: '2023-03-18T00:00:00.000Z',
        updatedAt: '',
    },
];
